// Generated by CoffeeScript 1.6.3
(function() {
  Array.prototype.remove = function(from, to) {
    var rest;
    rest = this.slice((to || from) + 1 || this.length);
    this.length = from < 0 ? this.length + from : from;
    return this.push.apply(this, rest);
  };

  Array.prototype.search = function(val) {
    var i, _i, _ref;
    for (i = _i = 0, _ref = this.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (this[i] === val) {
        return i;
      }
    }
    return null;
  };

}).call(this);

/*
//@ sourceMappingURL=array.map
*/
