// Generated by CoffeeScript 1.6.3
(function() {
  window.assert = function(b, msg) {
    if (!b) {
      throw new Error("assertion fail: " + msg);
    }
  };

}).call(this);

/*
//@ sourceMappingURL=utils.map
*/
