// Generated by CoffeeScript 1.6.2
(function() {
  window.assert = function(bool, msg) {
    if (!bool) {
      throw new Error("assertion failure: " + msg);
    }
  };

}).call(this);

/*
//@ sourceMappingURL=utils.map
*/
