// Generated by CoffeeScript 1.6.2
(function() {
  window.fillRect = function(gui, x, y) {
    return gui.graphics.fillRectangle(x * gui.BLOCK_WIDTH, y * gui.BLOCK_HEIGHT, gui.BLOCK_WIDTH, gui.BLOCK_HEIGHT);
  };

  window.colOf = Math.floor;

  window.rowOf = Math.floor;

}).call(this);

/*
//@ sourceMappingURL=world.map
*/
