// Generated by CoffeeScript 1.6.2
(function() {
  window.BotlangMode = (function() {
    return function() {
      return {
        startState: function() {
          return {
            indent: 0
          };
        },
        token: function(stream, state) {
          if (stream.peek() === "#") {
            stream.skipToEnd();
            state.indent = stream.indentation();
            return "comment";
          }
          if (stream.sol()) {
            if (stream.skipTo(':')) {
              state.indent = stream.indentation() + 4;
              return "atom";
            } else {
              state.indent = stream.indentation();
            }
          }
          stream.next();
          return "fun";
        },
        indent: function(state, textAfter) {
          return state.indent;
        }
      };
    };
  })();

}).call(this);

/*
//@ sourceMappingURL=mode.map
*/
